const projects = [
  {
    id: 1,
    title: 'valve de contrôle ',
    price: 850,
    image: '/images/valve de contrôle.jpeg',
    description: "valve de contrôle pneumatique pour système hydraulique de benn",
  },
  {
    id: 2,
    title: 'électrovanne hydraulique',
    price: 1400,
    image: '/images/électrovanne hydraulique.jpeg',
    description: "électrovanne hydraulique directionnelle, un composant essentiel.",
  },
  {
    id: 3,
    title: 'Distributeur 4/2',
    price: 900,
    image: '/images/Distributeur 42.jpeg',
    description: "Distributeur 4/2 voies (4 ports, 2 positions).",
  },
  {
    id: 4,
    title: 'Bloc électrovanne 2/2',
    price: 560,
    image: '/images/Bloc électrovanne 22.jpeg',
    description: "Bloc électrovanne 2/2, normalement fermé.",
  },
  {
    id: 5,
    title: 'vanne navette hydraulique',
    price: 400,
    image: '/images/vanne navette.jpeg',
    description: "Vanne navette hydraulique, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 6,
    title: 'valve d\'équilibrage double',
    price: 800,
    image: '/images/équilibrage double.jpeg',
    description: "Valve d'équilibrage double, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 7,
    title: 'vanne de séquence hydraulique',
    price: 650,
    image: '/images/vanne de séquence hydraulique.jpeg',
    description: "Vanne de séquence hydraulique, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 8,
    title: 'Commande hydraulique/pneumatique',
    price: 1400,
    image: '/images/Commande hydraulique.jpeg',
    description: "Commande hydraulique/pneumatique modulaire, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 9,
    title: 'Pompe à pistons à cylindrée',
    price: 5800,
    image: '/images/Pompe à pistons à cylindrée.jpeg',
    description: "Pompe à pistons à cylindrée, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 10,
    title: 'pompe hydraulique à engrenages',
    price: 6500,
    image: '/images/pompe hydraulique à engrenages.jpeg',
    description: "Pompe hydraulique à engrenages, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 11,
    title: 'pompe à pistons hydrauliques',
    price: 6500,
    image: '/images/pompe à pistons hydrauliques.jpeg',
    description: "Pompe à pistons hydrauliques, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 12,
    title: 'pompe à pistons hydrauliques avec pride',
    price: 4000,
    image: '/images/pompe à pistons hydrauliques avec pride.jpeg',
    description: "Pompe à pistons hydrauliques avec pride, composant essentiel pour les systèmes de transmission.",
  },
  {
    id: 13,
    title: 'distributeur hydraulique monobloc',
    price: 2600,
    image: '/images/distributeur hydraulique monobloc.jpeg',
    description: "Distributeur hydraulique monobloc, composant essentiel pour les systèmes de transmission.",
  },
];

export default projects;
